### ISSUE TITLE
6월 13일 치지직 업데이트 이후 그리드 없이 고화질 시청이 작동하지 않음.

### ISSUE THREAD

**Issue by majaksin** [Oein/chzzkExt#3]
# 6월 13일 치지직 업데이트 이후 그리드 없이 고화질 시청이 작동하지 않음.

## 문제
1. '치지직' 페이지로 이동
2. 그리드를 설치하지 않은 상태로 '1080/720p HD'를 활성화
3. 1080/720p 재생 불가

## 적용 환경
 - Device: Any
 - OS: Windows
 - Browser : Any
 - Extension Version : 2.1+

**Comment by Oein** [comment]
한국어로 작성해 주셔도 무방합니다. 열심히 방법을 찾아보고 있습니다!
